name: $(Major).$(Minor).$(Year:yy)$(DayOfYear).$(Rev:r)

trigger:
  branches:
    include:
    - main
    - refs/tags/release/*
  paths:
    include:
    - src/*
    - tests/*

pr:
  branches:
    include:
    - main
  paths:
    include:
    - src/*
    - tests/*
    
variables:
  - name: vmImageName
    value: 'windows-latest'

stages:

- stage: 'Build'
  variables:
    Solution: '**/*.sln'
    BuildConfiguration: 'Release'
    ${{ if ne(startsWith(variables['Build.SourceBranch'], 'refs/tags/release')) }}:
      Version: '$(Build.BuildNumber)-dev'
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/release') }}:
      Version: '$(Build.BuildNumber)'

  jobs:
  - job:
    pool:
      vmImage: $(vmImageName)

    workspace:
      clean: all

    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'
      inputs:
        versionSpec: '5.6.0'
    
    - task: NuGetCommand@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        restoreSolution: '$(Solution)'

    - task: VersionDotNetCoreAssemblies@2
      displayName: 'Set assembly version number'
      inputs:
        Path: '$(Build.SourcesDirectory)'
        VersionNumber: '$(Version)'
        Injectversion: False
        VersionRegex: '\d+\.\d+\.\d+\.\d+(?:-[a-z]+)?'
        FilenamePattern: '.csproj'
        SDKNames: 'Microsoft.NET.Sdk,MSBuild.Sdk.Extras'
        OutputVersion: 'OutputedVersion'

    - task: MSBuild@1
      displayName: 'Build solution'
      inputs:
        solution: '$(Solution)'
        platform: 'Any CPU'
        configuration: $(BuildConfiguration)
        maximumCpuCount: true

    - task: DotNetCoreCLI@2
      displayName: 'Run unit tests'
      inputs:
        command: 'test'
        arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/UnitTests.cobertura.xml'
        projects: '**/*UnitTests*.csproj'
        testRunTitle: 'Unit Tests'

    - task: reportgenerator@4
      displayName: 'Generate code coverage report'
      inputs:
        reports: '$(Build.SourcesDirectory)/TestResults/Coverage/*.cobertura.xml'
        targetdir: '$(Build.SourcesDirectory)/CoverageResults'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(Build.SourcesDirectory)/CoverageResults/Cobertura.xml'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/src'
        Contents: |
          **/*.nupkg
          **/*.snupkg
        TargetFolder: '$(Build.ArtifactStagingDirectory)/artifacts'

    - publish: '$(Build.ArtifactStagingDirectory)/artifacts'
      artifact: 'artifacts'

- stage: 'Publish'
  dependsOn: 'Build'
  condition: succeeded()
  jobs:
    - job:
      pool:
        vmImage: $(vmImageName)

      steps:
      - checkout: none

      - download: current
        artifact: 'artifacts'

      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'NuGet - MADE Apps'